# Introduction to Julia


Julia is a programming language, suitable for a wide range of things, but especially well-developed for scientific applications. You are currently using a `Jupyter` notebook. Jupyter notebooks are an interactive interface for **ju**lia, **pyt**hon, and **r**, i.e. give it commands, look at the output, give new commands, etc.. Jupyter notebooks are a browser-based interface that can render text, code, and plots in one file, making it possible to produce documents that explain how you develop your model, how your code works, and what the results are. The text cells use [Markdown](https://daringfireball.net/projects/markdown/syntax) for formatting, which is an efficient mark-up language that is now integrated in many platforms.

A Jupyter notebook has different types of cells (you can look at the drop down menu above to see what they are). You will mostly use Markdown and Code. Markdown is what you use for formatted text. Code is what you use for, well, code. In either case, using `Shift + Enter` will evaluate the cell (in the case of Markdown, it will format your text). NB RawConvert is for code that's not evaluated. Hitting Enter by itself will start a new line in the same cell.

Click on this cell to see the code that produced it. 

Now evaluate the cell by pressing `Shift + Enter`

Now type in the cell below: `this is my first *markdown line*`

You can also use $\LaTeX$ in the notebook. Here's an example: $\int_{x=0}^{x=1} f(x)dx$. Here's a $\LaTeX$ expression in its own line: $$\sum_{n=1}^\inf 1/n$$
Here's more about using [Markdown in Jupyter](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Working%20With%20Markdown%20Cells.html)

Ok, let's write some code.

In [1]:
# define a variable (in Python, # is the symbol for comments, i.e., stuff that comes after # is not evaluated)
x = 3

3

In [2]:
# Now when we call up x, Python will give us its value that we just assigned
x

3

In [3]:
# We can do operations on x (here: multiplication, power, increase by)
[2*x, x^2, x+=1]

3-element Array{Int64,1}:
 6
 9
 4

The square brackets `[]` in Julia denote a list, which is a list of things. 

You can define an array as follows:

In [4]:
zeros(Float64, 2, 3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [5]:
a = ones(Int, 2*x, x^2)

8×16 Array{Int64,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1

Arrays are useful because you can conduct operations on all elemements simultaneously.

In [6]:
2*a

8×16 Array{Int64,2}:
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2

In [7]:
(a .+ 1).^ 2

8×16 Array{Int64,2}:
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4

Note that we write `.+` and `.^`. The dot indicates that the operation (addition and power) are performed to each element of `a`. 

You can also set up an array manually:

In [8]:
b = [2 3 7; 4 5 8]

2×3 Array{Int64,2}:
 2  3  7
 4  5  8

You can querry elements of arrays using the square brackets:

In [9]:
b[1]

2

In [10]:
b[1,3] # return value in row 1 and column 3 

7

In [11]:
b[2,:]

3-element Array{Int64,1}:
 4
 5
 8

Note that the `:` indicates that we want to retrieve all values of row `2`. 

Ok, now let's model something. Simplest model: geometric population growth, the trajectory of a population growing geormetrically for 100 generations  starting from an initial value 1000, and increasing each generation by a factor of 1.01.

In [12]:
pop_hist = zeros(100); # make an array with zeros of length 100 
pop_hist[1] = 1000; # set the first element of the array to your initial population size
for i in 2:100 # this makes a loop, using the index i, and for each successive value of it from 1 to 99 evaluating what comes after
    pop_hist[i] = pop_hist[i-1]*1.01 # takes the previous element of the array (i.e. pop size last time step), multiplies it with 1.01 and assigns that value to the curret position in the array
end
pop_hist[1:6]

6-element Array{Float64,1}:
 1000.0      
 1010.0      
 1020.1      
 1030.301    
 1040.60401  
 1051.0100501

Now let's plot it. To that we need to load the plotting environment Plotly.

In [13]:
#using Pkg
#using Plots
#plotlyjs() # Choose the Plotly.jl backend for web interactivity

In [14]:
#PlotlyJS.plot(pop_hist)

Done! We have produced a population model, be it simple, in Julia. Note that we could have done this more easily in one line using the fact that Julia knows how to automatically distribute many operations on elements of an array:

In [15]:
pop_hist1 = 1000 .* (1.01 .^ (0:100));
pop_hist1[1:6]

6-element Array{Float64,1}:
 1000.0            
 1010.0            
 1020.1            
 1030.3010000000002
 1040.60401        
 1051.0100501000002